# Generated by Django 4.2.3 on 2023-07-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('microsaas_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('how_it_works', models.TextField()),
                ('business_model', models.TextField()),
                ('target_audience', models.TextField()),
                ('competitive_edge', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
